// Generated by CoffeeScript 1.10.0
(function() {
  var countdown, food, foods, i, len, nfl, num, number;

  eric(function() {
    return console.log('eric');
  });

  sum(function(x, y) {
    return x + y;
  });

  nfl = {
    atl: 'falcons',
    det: 'lions',
    gb: 'packers'
  };

  if (true || false) {
    console.log('logs');
  } else {
    console.log('not');
  }

  foods = ['broccoli', 'spinach', 'chocolate'];

  for (i = 0, len = foods.length; i < len; i++) {
    food = foods[i];
    if (food !== 'chocolate') {
      console.log(food);
    }
  }

  number = 100;

  countdown = (function() {
    var j, results;
    results = [];
    for (num = j = 10; j >= 1; num = --j) {
      results.push(num);
    }
    return results;
  })();

}).call(this);
