// Generated by CoffeeScript 1.10.0
(function() {
  var checkRows, gameBoard;

  gameBoard = [['', '', ''], ['', '', ''], ['', '', '']];

  checkRows = function(board) {
    var checkRow, i, len, result, row;
    for (i = 0, len = board.length; i < len; i++) {
      row = board[i];
      result = checkRow(row);
      if (result === 'O') {
        'O';
      }
      if (result === 'X') {
        'X';
      } else {
        null;
      }
    }
    return checkRow = function(row) {
      var O, X, j, len1, square;
      X = 0;
      O = 0;
      for (j = 0, len1 = row.length; j < len1; j++) {
        square = row[j];
        if (square === 'X') {
          X++;
        }
        if (square === 'O') {
          O++;
        }
      }
      if (X === 3) {
        'X';
      }
      if (O === 3) {
        return 'O';
      }
    };
  };

}).call(this);
